baseURL = "https://deviq.com/"
languageCode = "en-us"
title = "DevIQ"

enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Software development reference and learning"

  favicon = "favicon.png"

  [params.navbar]
    displayTitle = false
    displayLogo = true
    [params.navbar.logo]
      path = "images/banner.png"
      width = "120"
      height = "40"
      link = "/"

  [params.theme]
    default = "system"
    displayToggle = true

  [params.footer]
    enable = true
    displayCopyright = true
    displayPoweredBy = false

  [params.search]
    enable = true
    type = "flexsearch"

  [params.mermaid]
    base = "https://cdn.jsdelivr.net/npm/mermaid"

[menu]
  [[menu.main]]
    identifier = "NimblePros"
    name = "NimblePros"
    url = "https://nimblepros.com"
    weight = 1
  [[menu.main]]
    identifier = "theme-toggle"
    weight = 100
    [menu.main.params]
      type = "theme-toggle"

  [[menu.sidebar]]
    name = "Design Patterns"
    pageRef = "/design-patterns"
    weight = 10
  [[menu.sidebar]]
    name = "Principles"
    pageRef = "/principles"
    weight = 20
  [[menu.sidebar]]
    name = "Practices"
    pageRef = "/practices"
    weight = 30
  [[menu.sidebar]]
    name = "Antipatterns"
    pageRef = "/antipatterns"
    weight = 40
  [[menu.sidebar]]
    name = "Domain-Driven Design"
    pageRef = "/domain-driven-design"
    weight = 50
  [[menu.sidebar]]
    name = "Laws"
    pageRef = "/laws"
    weight = 60
  [[menu.sidebar]]
    name = "Testing"
    pageRef = "/testing"
    weight = 70
  [[menu.sidebar]]
    name = "Architecture"
    pageRef = "/architecture"
    weight = 80
  [[menu.sidebar]]
    name = "Values"
    pageRef = "/values"
    weight = 90
  [[menu.sidebar]]
    name = "Terms"
    pageRef = "/terms"
    weight = 100
  [[menu.sidebar]]
    name = "Tools"
    pageRef = "/tools"
    weight = 110
  [[menu.sidebar]]
    name = "Code Smells"
    pageRef = "/code-smells"
    weight = 120
